name: Security CI (Semgrep + Snyk)

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install semgrep
        run: pip install semgrep
      - name: Run semgrep
        run: semgrep --config .semgrep.yml --output semgrep-results.json || true
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.json

  snyk:
    name: Snyk dependency scan
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Install Snyk
        uses: snyk/actions/setup@v2
      - name: Auth Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN
      - name: Run snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=high
      - name: Snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects
